# Generated by Django 5.1.6 on 2025-03-19 20:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_name", models.CharField(max_length=255)),
                (
                    "default_account_code",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("issuer_organisation", models.CharField(max_length=255)),
                (
                    "device_fuel",
                    models.CharField(
                        choices=[
                            ("ES200", "Wind"),
                            ("ES201", "Solar"),
                            ("ES202", "Hydro"),
                            ("ES203", "Geothermal"),
                            ("ES204", "Biomass"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "device_technology",
                    models.CharField(
                        choices=[
                            ("TC210", "Onshore"),
                            ("TC211", "Offshore"),
                            ("TC212", "Photovoltaic"),
                            ("TC213", "Concentrated Solar Power"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "capacity",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(1e-06)],
                    ),
                ),
                ("commissioning_date", models.DateField()),
                ("requested_effective_registration_date", models.DateField()),
                (
                    "other_labelling_scheme",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("address", models.CharField(max_length=255)),
                ("state_province", models.CharField(max_length=255)),
                ("postcode", models.CharField(max_length=20)),
                ("country", models.CharField(max_length=100)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "production_facility_registration",
                    models.FileField(
                        null=True, upload_to="device_documents/facility_registration/"
                    ),
                ),
                (
                    "declaration_of_ownership",
                    models.FileField(
                        null=True, upload_to="device_documents/ownership_declaration/"
                    ),
                ),
                (
                    "metering_evidence",
                    models.FileField(
                        null=True, upload_to="device_documents/metering_evidence/"
                    ),
                ),
                (
                    "single_line_diagram",
                    models.FileField(
                        null=True, upload_to="device_documents/single_line_diagram/"
                    ),
                ),
                (
                    "project_photos",
                    models.FileField(
                        null=True, upload_to="device_documents/project_photos/"
                    ),
                ),
                ("additional_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
